# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='identity',
        ),
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.IntegerField(default=0),
        ),
    ]
