# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161211_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='query',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added'),
            preserve_default=False,
        ),
    ]
